name: tusk_storage
description: "Storage for data"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0
  image_picker: ^1.0.7
  flutter_colorpicker: ^1.0.3
  path_provider: ^2.1.2
  file_picker: ^8.0.0
  cupertino_icons: ^1.0.8

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  android_icon_background: "#000000"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.png"

flutter_native_splash:
  color: "#000000"
  image: assets/icon.png
  android: true
  ios: true
  android_12:
    image: assets/icon.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/splash.png
